### ISSUE TITLE
Oscillatord 3.4.5 segfault

### ISSUE THREAD

**Issue by leoleovich** [Orolia2s/oscillatord#101]
Oscillatord 3.4.5 is segfaulting

**Comment by agagniere** [comment]
OK, do you have some logs ?

**Comment by leoleovich** [comment]
Yes @agagniere if you check chat there are logs waiting for you.

**Comment by agagniere** [comment]
Indeed
> https://gist.github.com/leoleovich/3809de270fcad815142cc52dedb64e00
