### ISSUE TITLE
monitoring: Don't stick on IPv4-only solution

### ISSUE THREAD

**Issue by vvfedorenko** [Orolia2s/oscillatord#110]
`listen_inet_socket()` uses `inet_addr()` to resolve string to sockaddr_in. This limits us to use IPv4 addresses only. This is hard limitation in 2023, let's remove it and use proper interfaces like `getadrinfo()`

**Comment by vvfedorenko** [comment]
The issue is now more urgent. We have fedora build test fails:
https://artifacts.dev.testing-farm.io/6a417119-d90a-46f9-b031-a50be17449f3/work-rpminspectmqcjny9z/rpminspect/execute/data/guest/default-0/rpminspect-1/data/viewer.html#

Could you please fix it ASAP?

**Comment by leoleovich** [comment]
cc @agagniere can you please take a look ASAP or this build could be banned from Fedora repos.
