### ISSUE TITLE
Oscillatord 3.5 does not show "disciplining" parameters for CLS timecard.

### ISSUE THREAD

**Issue by SatyaVarmaK** [Orolia2s/oscillatord#111]
After updating to Oscillatord 3.5  we can no longer get the "disciplining" parameters  for CLS time card. We check if one of the sub parameters  "ready_for_holdover"   is true or false and based on the result we start the holdover test or continue disciplining the Time Card.
Even though we set "disciplining: false" in oscillatord config file, can the "ready_for_holdover" parameter be added regardless of the config file parameters?

![image](https://user-images.githubusercontent.com/100011728/227094926-97f58ebc-e2cf-4ac1-90a7-0da6f697265e.png)

**Comment by agagniere** [comment]
Fixed by #113
