### ISSUE TITLE
GNSS configuration update

### ISSUE THREAD

**Issue by vvfedorenko** [Orolia2s/oscillatord#19]
Right now it takes up to 12 minutes to reconfigure GNSS receiver and get first signal from it. But actually we need no reconfigure it once after host power up. It would be great if oscillatord could check GNSS receiver configuration at start up and apply only difference to it. It will greatly reduce the speed up time in case of software restart

**Comment by CharlesParent** [comment]
All Revision 4 cards we shipped have their gnss receiver reconfigured during tests before shipping. You may turn this feature off by setting `gnss_receiver_reconfigure` to false.

This is a good feature to implement though.

**Comment by leoleovich** [comment]
@CharlesParent unfortunately this is not enough. We need to make sure receiver always has up to date configuration to override manual changes or new version of the configuration.

**Comment by CharlesParent** [comment]
Hi @leoleovich,
This has been added in https://github.com/Orolia2s/oscillatord/commit/bea2c316fc9ae71732789d2c8917637362421c91
