### ISSUE TITLE
Removing gnss-cable-delay causes an error and not sets it to 0

### ISSUE THREAD

**Issue by leoleovich** [Orolia2s/oscillatord#69]
```
Jul 26 06:15:15 srv oscillatord[117392]: 06:15:15 #033[33mWARN #033[0m Error parsing gnss-cable-delay value
```
Missing option should act as 0 IMHO.
Currently setting to 0 doesn't send an update (I had to set 1).

**Comment by CharlesParent** [comment]
Currently missing option leaves GNSS config as is.
Default Antenna cable delay set in config is _50ns_. I think missing option should leave default configuration as is

I will check why setting value to zero does not send and update.

**Comment by CharlesParent** [comment]
Fixed in https://github.com/Orolia2s/oscillatord/commit/742d33f7667eefd88153acbdf6a4577cce6b8abd
