### ISSUE TITLE
Always set "clock": { "class": "X", "offset": Y } values

### ISSUE THREAD

**Issue by leoleovich** [Orolia2s/oscillatord#97]
In 3.4.4 these values are missing when mRO-50 is initializing. We have to have these values populated, even if these are just defaults.
Please always keep compatibility with the tools relying on the API https://github.com/facebook/time/blob/main/oscillatord/monitoring.go#L174-L189

**Comment by agagniere** [comment]
With our oscillator the problem was not reproducible, but I expect this simple fix to address your immediate issue.

**Comment by agagniere** [comment]
> I can confirm we now see the clock monitoring section
